<<<<<<< HEAD
model:
  num_classes: 2
  freeze_backbone: false

data:
  temporal_dim: 3
  img_size: 256
  no_data_value: -9999
  constant_multiplier: 1.0
  reduce_to_zero: false
  replace_label:
    - -9999
    - -1
  bands:
    - 0  # Blue
    - 1  # Green
    - 2  # Red
    - 3  # NIR
    - 4  # SWIR1
    - 5  # SWIR2

regions:
  East Africa:
    center: [5.0, 35.0]
    bbox: [-5, 20, 15, 50]
  West Africa:
    center: [12.0, 0.0]
    bbox: [0, -20, 25, 20]
  North Africa:
    center: [25.0, 15.0]
    bbox: [15, -20, 35, 50]
  Middle East:
    center: [25.0, 45.0]
    bbox: [15, 35, 35, 55]

earthdata:
  username: "shenghuei"
=======
model:
  num_classes: 2
  freeze_backbone: false

data:
  temporal_dim: 3
  img_size: 256
  no_data_value: -9999
  constant_multiplier: 1.0
  reduce_to_zero: false
  replace_label:
    - -9999
    - -1
  bands:
    - 0  # Blue
    - 1  # Green
    - 2  # Red
    - 3  # NIR
    - 4  # SWIR1
    - 5  # SWIR2

regions:
  East Africa:
    center: [5.0, 35.0]
    bbox: [-5, 20, 15, 50]
  West Africa:
    center: [12.0, 0.0]
    bbox: [0, -20, 25, 20]
  North Africa:
    center: [25.0, 15.0]
    bbox: [15, -20, 35, 50]
  Middle East:
    center: [25.0, 45.0]
    bbox: [15, 35, 35, 55]

earthdata:
  username: "shenghuei"
>>>>>>> f4ef771 (add vz)
  password: "G3A7$zKGp&i_j%=" 